### ISSUE TITLE
Lyrics no longer show

### ISSUE THREAD

**Issue by Martinsbane** [naaando/lyrics#39] opened 2020-05-27 07:47 UTC
i use the lyrics app on elementary and recently, the app doesn't show lyrics again while another app (give me lyrics) would show lyrics for the same song(it shows couldn't find lyrics)

**Comment by bipox** [comment] 2020-09-06 10:47
In my case, title, album and artist are correctly filled in but no lyrics appear. Instead "Téléchargement" ("download" in french) is written.

**Comment by naaando** [comment] 2021-01-26 12:52
Duplicate of #35

**Closed by naaando** 2021-01-26 12:52 UTC
